---
title: "Analyses of Socium Coauthorship Network"
author: "Christine Hedde - von Westernhagen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center")

library(worcs)
library(here)
library(dplyr)
library(tidygraph)
library(ggraph)
```

```{r data}
net_soc <- readRDS(here("data-processed", "net_soc.rds"))
```

## Department Assortativity

```{r plot}
ggraph(net_soc, layout = "fr") +
  geom_edge_link() +
  geom_node_point(aes(fill = as.factor(dep_cat)), 
                  shape = 21, size = 2) +
  labs(fill = "Department", caption = "Co-authorship network of SOCIUM members.") +
  theme_graph(base_family="sans")
```

```{r assortativity}
assort_coef <- net_soc %>% 
  activate(nodes) %>% 
  mutate(assort = graph_assortativity(dep_cat, directed = FALSE)) %>% 
  pull(assort) %>% 
  unique()
```

The coefficient for department assortativity is **`r round(assort_coef, 3)`**, meaning: co-authorship is far more prevalent within than between departments.
